Update

diff --git a/i3blocks/cpu b/i3blocks/cpu
--- a/i3blocks/cpu
+++ b/i3blocks/cpu
@@ -1,48 +1,40 @@
-#!/usr/bin/env perl
-
-use strict;
-use warnings;
-use Getopt::Long;
+#!/bin/bash
 
 # Default values
-my $t_warn = $ENV{T_WARN} // 50;
-my $t_crit = $ENV{T_CRIT} // 80;
-my $cpu_usage = -1;
-my $label = $ENV{LABEL} // "";
-my $color_normal = "#FFFFFF";  # Bianco
-my $color_warn = "#FFFFFF";    # Bianco
-my $color_crit = "#FFFFFF";    # Bianco
+t_warn=${T_WARN:-50}
+t_crit=${T_CRIT:-80}
+cpu_usage=-1
+label=${LABEL:-""}
+color_normal="#FFFFFF"  # Bianco
+color_warn="#FFFFFF"    # Bianco
+color_crit="#FFFFFF"    # Bianco
 
-sub help {
-    print "Usage: cpu_usage [-w <warning>] [-c <critical>]\n";
-    print "-w <percent>: warning threshold to become yellow\n";
-    print "-c <percent>: critical threshold to become red\n";
-    exit 0;
+function help {
+    echo "Usage: cpu_usage [-w <warning>] [-c <critical>]"
+    echo "-w <percent>: warning threshold to become yellow"
+    echo "-c <percent>: critical threshold to become red"
+    exit 0
 }
 
-GetOptions("help|h" => \&help,
-           "w=i"    => \$t_warn,
-           "c=i"    => \$t_crit,
-);
+while getopts "hw:c:" opt; do
+    case "$opt" in
+        h) help ;;
+        w) t_warn=$OPTARG ;;
+        c) t_crit=$OPTARG ;;
+        \?) help ;;
+    esac
+done
 
 # Get CPU usage
-$ENV{LC_ALL} = "en_US";  # If mpstat is not run under en_US locale, things may break, so make sure it is
-open (MPSTAT, 'mpstat 1 1 |') or die;
-while (<MPSTAT>) {
-    if (/^.*\s+(\d+\.\d+)[\s\x00]?$/) {
-        $cpu_usage = 100 - $1;  # 100% - %idle
-        last;
-    }
-}
-close(MPSTAT);
+export LC_ALL="en_US"  # If mpstat is not run under en_US locale, things may break, so make sure it is
+cpu_usage=$(mpstat 1 1 | awk '$12 ~ /^[0-9.]+$/ { print 100 - $12 }')
 
-$cpu_usage eq -1 and die "Can't find CPU information";
+[[ "$cpu_usage" == "-1" ]] && echo "Can't find CPU information" && exit 1
 
 # Print short_text, full_text
-printf " ${label}%.0f%%\n", $cpu_usage;
+printf " ${label}%.0f%%\n" "$cpu_usage"
 
 # Print color (always white)
-print "${color_normal}\n";
+echo "$color_normal"
 
-exit 0;
-
+exit 0
